plugins {
    id 'java'
    id 'application'
}

group = 'br.com.bullla'
version = '1.0.0'
sourceCompatibility = '21'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
}

application {
    mainClass = 'br.com.bullla.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'br.com.bullla.Main'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}